version: '3.8'

services:
  # Flask-интерфейс
  flask-web:
    build: .
    ports:
      - "5001:5000"
    networks:
      - qa-network
    depends_on:
      - mysql-db

  # база данных MySQL
  mysql-db:
    image: mymysql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "2250:3306"
    networks:
      - qa-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my_local_notes:/home/notes/shared # бинд новой папки

networks:
  qa-network:
    driver: bridge

volumes:
  mysql_data:
