name: QA-Check-Pipeline
on: [push]
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check YAML syntax
        run: |
          echo "Проверка манифестов Kubernetes..."
          cat k8s/app-stack.yml
      - name: Run Mock Tests
        run: echo "Все автотесты пройдены успешно! ✅"
